# Tool versions - update these to upgrade tools
fzf_version: "0.66.0"
neovim_version: "0.11.5"
aqua_installer_version: "4.0.2"

# Mise global tools (managed by aqua)
mise_global_tools:
  - "aqua:fd"
  - "aqua:ripgrep"
  - "aqua:bat"
  - "aqua:delta"
  - "aqua:lsd"

# System packages to install
system_packages:
  - zsh
  - bfs

# Dotfiles repository
dotfiles_repo: "git@github.com:cstrahan/dotfiles.git"
